### ISSUE TITLE
Nano-slcan

### ISSUE THREAD

**Issue by Memfispro** [mintynet/nano-can#2]
Hi. I have a question. Nano-slcan.ino works on the program canhacker?
If it works then what is the probability of the reliability program?

**Comment by mintynet** [comment]
NANO-SLCAN.INO uses the LAWICEL protocol but see the note below.
Nano-slcan.ino can be recompiled to other arduino boards but I cannot guarantee it will work without some modification. SLCAND does not always initialize correctly when using the ch340 serial driver on cheap nano clones, I know that the new 'nano 33 iot' works fine with SLCAND but that involves modifying the pcb and swapping the CAN transceiver to a SN65HVD230DR.
